version: '3.8'
services:

  filebrowser:
    image: hurlenko/filebrowser
    user: "root:root"
    ports:
      - 443:8080
    volumes:
      - /CONFIG_DIR:/config

      # Services Volumes
      - reporting-vol:/data/services/reporting:ro
      # - digital-vol:/data/services/digital:ro
      # - admin_panel_services-vol:/data/services/admin_panel_services:ro

      # Services Volumes
      - reporting_package-vol:/data/services_packages/reporting:ro

      #
      - rsa_vol:/data/rsa:ro  
      - master_vol:/data/master_files
      # - master_vol:/data/app/files:ro
      - ngmy_vol:/data/ngmypackage:ro
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
    networks:
      - internal-network



  rabbitmq_server:
    container_name: rabbitmq_server
    image: rabbitmq:3-management
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672
    networks:
      - internal-network




volumes:

  # Services
  reporting-vol:
    external: true
  digital-vol-vol:
    external: true
  admin_panel_services-vol:
    external: true


  # packages
  reporting_package-vol:
    external: true


  
  rsa_vol: 
    name: rsa_files
    driver: local
    driver_opts:
      type: none
      device: ./rsa
      o: bind
  master_vol: 
    name: master_files
    driver: local
    driver_opts:
      type: none
      device: ./files
      o: bind

  ngmy_vol: 
    name: ngmy_packages
    driver: local
    driver_opts:
      type: none
      device: ./packages
      o: bind

networks:
  internal-network:
    driver: bridge
    name: base_network

    # labels:
      # com.docker.compose.network: "network" 