version: '3.7'
x-minio-common: &minio_common
  container_name: minio
  image: quay.io/minio/minio:latest
  command: server /data --console-address ":9090"
  ports:
    - '9000:9000'
    - '9090:9090'
  networks:
    - minio-network
  volumes:
    - 'minio_data:/data'
  environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER:-ROOTNAME}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-CHANGEME123}
    - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS:-devbucket2}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/healch/live"]
    interval: 30s
    timeout: 20s
    retries: 5
    start_period: 30s
  
services:
  minio1:
    <<: *minio_common
    # networks:
    # - my_networ
    # hostname: minio1
    # volumes:
    #   - type: bind
    #     source: minio_data
    #     target: /mtn/data
      

networks:
  minio-network:
    name: base_network
    external: true

volumes:
  minio_data:
    driver: local