version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9210:9200
      - 9310:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false