version: '3.8'
services:
  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: local_mailpit
    ports:
      - "8025:8025"
    networks:
      - mail-network
networks:
  mail-network:
    driver: bridge
    name: base_network
    external: true

