version: '3.8'

services:
  mongodb:
      image: mongo:latest
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-ROOTNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-ROOTNAME}
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db
      networks:
        - internal-network
  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4321:4321"
    environment:
    - MONGO_URL=mongodb://${MONGO_USERNAME:-ROOTNAME}:${MONGO_PASSWORD:-ROOTNAME}@${MONGO_HOST:-mongodb}:${MONGO_PORT:-27017}


    

volumes:
  mongodb_data_container:

networks:
  internal-network:
    driver: bridge
    name: base_network
    external: true


