version: '3.8'
services:

  filebrowser:
    image: hurlenko/filebrowser
    user: "root:root"
    ports:
      - 443:8080
    volumes:
      - master_files:/data
      - /CONFIG_DIR:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

  rabbitmq_server:
    image: rabbitmq:3-management
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672
    networks:
      - internal-network



volumes:
  rsa: 
    driver: local
    driver_opts:
      type: none
      device: ./rsa
      o: bind
  master_files: 
    driver: local
    driver_opts:
      type: none
      device: ./files
      o: bind


networks:
  internal-network:
    driver: bridge
    name: base_network
    # labels:
      # com.docker.compose.network: "network" 