version: '3.8'
services:  
  redis:
    container_name: redis
    image: redis:6.2.13-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      -  redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    networks:
      - redis-network

networks:
  redis-network:
    name: base_network
    external: true


  