version: '3.8'
services:
  # app3: 



  worker: #&wokermain
    # Build using the worker Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.worker
    # Need to access the database
    # OPTIONAL: If you worker needs to access your db that is deployed
    # locally, then make the network mode as host.
    # network_mode: host
    # Pass the rabbitmq_uri as env varible in order to
    # connect to our service
    
    environment:
      # NOTE: Below we are using 127.0.0.1 because this container
      # will run on the host network, thus it will have access to the
      # host network.
      # If it would not have run locally, we would have had to
      # connect using the service name like following:
      # amqp:rabbitmq_server:5672
      rabbitmq_uri: amqp://127.0.0.1:5672
    # depends_on: 
    #   - rabbitmq_server
    # volumes:
    #   - app_volume:/app
    networks:
      - celery-network
    entrypoint: "tail -f /dev/null"
    volumes:
      - app_volume:/app
    working_dir: /app/app

  # worker2:
  #   <<: *wokermain

volumes:
  app_volume:
    name: app_volume
    external: true

networks:
  celery-network:
    driver: bridge
    name: base_network
    external: true


