version: "3.9"

services:
  main_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn local:app --host 0.0.0.0 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"