version: "3.8"
services:
  mockServer:
    image: mockserver/mockserver:latest
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_LOG_LEVEL: TRACE
      MOCKSERVER_PERSIST_EXPECTATIONS: "true"
      MOCKSERVER_PERSISTED_EXPECTATIONS_PATH: /config/persistedExpectations.json
      # MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/persistedExpectations.json
      
      # MOCKSERVER_PROPERTY_FILE: "/config/mockserver.custom2.properties"
      # MOCKSERVER_SERVER_PORT: 80
      # MOCKSERVER_LOG_LEVEL: TRACE
    volumes:
      - ./mock_server_config:/config
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /config
    # networks:
    #   - local-network

    labels:
      - "traefik.enable=true"
      - "treafik.http.routers.mockserver.rule=Host(`mock.localhost`)"
      - "treafik.http.services.mockserver.loadbalancer.server.port=1080"

networks:
  local-network:
    name: base_network
    external: true